version: "3"
services:
#  nginx:
#    build:
#      context: ./services/nginx
#      args:
#        NGINX_VERSION: nginx:${NGINX_VERSION}
#        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
#        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
#    container_name: nginx
#    ports:
#      - "${NGINX_HTTP_HOST_PORT}:80"
#      - "${NGINX_HTTPS_HOST_PORT}:443"
#    volumes:
#      - ${SOURCE_DIR}:/www/:rw
#      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
#      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
#      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
#      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
#      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
#      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
#    environment:
#      TZ: "$TZ"
#    restart: always
#    networks:
#      - default


#  mysql:
#    image: mysql:${MYSQL_VERSION}
#    container_name: mysql
#    ports:
#      - "${MYSQL_HOST_PORT}:3306"
#    volumes:
#      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
#      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
#    restart: always
#    networks:
#      - default
#    environment:
#      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
#      TZ: "$TZ"

  es01:
    build:
      context: ./services/elasticsearch
      args:
        ELASTICSEARCH_VERSION: ${ELASTICSEARCH_VERSION}
        ELASTICSEARCH_PLUGINS: ${ELASTICSEARCH_PLUGINS}
    container_name: es01
    environment:
      - TZ=$TZ
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - ${DATA_DIR}/esdata/es01:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_CONF_FILE_ONE}:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ELASTICSEARCH_LOG_DIR_ONE}:/usr/share/elasticsearch/logs
    hostname: es01
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    ports:
      - "${ELASTICSEARCH_CLIENT_HOST_PORT_ONE}:9200"
      - "${ELASTICSEARCH_SERVER_HOST_PORT_ONE}:9300"
      -
  es02:
    build:
      context: ./services/elasticsearch
      args:
        ELASTICSEARCH_VERSION: ${ELASTICSEARCH_VERSION}
        ELASTICSEARCH_PLUGINS: ${ELASTICSEARCH_PLUGINS}
    container_name: es02
    environment:
      - TZ=$TZ
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - ${DATA_DIR}/esdata/es02:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_CONF_FILE_TWO}:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ELASTICSEARCH_LOG_DIR_TWO}:/usr/share/elasticsearch/logs
    hostname: es02
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    ports:
      - "${ELASTICSEARCH_CLIENT_HOST_PORT_TWO}:9200"
      - "${ELASTICSEARCH_SERVER_HOST_PORT_TWO}:9300"
  es03:
    build:
      context: ./services/elasticsearch
      args:
        ELASTICSEARCH_VERSION: ${ELASTICSEARCH_VERSION}
        ELASTICSEARCH_PLUGINS: ${ELASTICSEARCH_PLUGINS}
    container_name: es03
    environment:
      - TZ=$TZ
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - ${DATA_DIR}/esdata/es03:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_CONF_FILE_THREE}:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ELASTICSEARCH_LOG_DIR_THREE}:/usr/share/elasticsearch/logs
    hostname: es03
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    ports:
      - "${ELASTICSEARCH_CLIENT_HOST_PORT_THREE}:9200"
      - "${ELASTICSEARCH_SERVER_HOST_PORT_THREE}:9300"
  kibana:
    image: kibana:${KIBANA_VERSION}
    container_name: kibana
    environment:
      TZ: "$TZ"
      elasticsearch.hosts: http://es02:9201
      I18N_LOCALE: "${KIBANA_I18N_LOCALE}"
    hostname: kibana
    depends_on:
      - es02
    restart: always
    ports:
      - "${KIBANA_HOST}:5601"
    networks:
      - elastic
  logstash:
    image: logstash:${LOGSTASH_VERSION}
    container_name: logstash
    hostname: logstash
    restart: always
    depends_on:
      - es03
    environment:
      TZ: "$TZ"
    ports:
      - "${LOGSTASH_HOST_PORT_C}:9600"
      - "${LOGSTASH_HOST_PORT_S}:5044"
    networks:
      - elastic
networks:
  default:
  elastic:
    driver: bridge
